#FROM homeassistant/armv7-homeassistant:stable
FROM homeassistant/raspberrypi4-64-homeassistant:stable


WORKDIR /scripts
COPY scripts/. .

CMD /bin/bash start.sh
#CMD python -m homeassistant --config /config
