version: '2.1'

volumes:
  volume_homeassistant:

services:
  homeassistant:
    build:
      context: ./
    volumes:
      - volume_homeassistant:/config
    #privileged: true
    ports:
      - 8123:8123
