FROM balenalib/%%BALENA_MACHINE_NAME%%-python:latest-build

RUN apt-get update
RUN apt-get install -y python3 python3-dev python3-pip libffi-dev libssl-dev python3-setuptools
RUN pip3 install wheel
RUN pip3 install homeassistant
CMD hass -c /config
